[package]
name = "AudioWAVGeneration"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "notSinWaves"
path = "src/DifferentWaves/notSinWaves.rs"
[[bin]]
name = "ChoiceOfWave"
path = "src/DifferentWaves/ChoiceOfWave.rs"

[dependencies]
